# Site settings
title: kittybiome
header-img: img/home-bg.jpg
email: team@kittybiome.com
description: "Kittybiome is a nonprofit company founded with the mission of understanding the microbiology of cats and improving cat health."
baseurl: ""
url: "http://www.kittybiome.com"
twitter_username: kittybiome
github_username:  kittybiome

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
